/**
 * LexGuard AI — Mastra → OpenTelemetry Observability Bridge
 *
 * Mastra ships its own native tracing system (span types for agent runs, tool
 * calls, model generations, workflow steps, etc.) but it was never wired up in
 * this app — `new Mastra({...})` never received an `observability` config, so
 * Mastra silently ran with a no-op tracer (no warning logged, unlike the
 * storage no-op which does warn).
 *
 * Rather than run a second, disconnected tracing backend, this exporter
 * re-emits every Mastra span as a real OpenTelemetry span on the same
 * NodeSDK tracer provider already initialized in tracer.ts — so Mastra's
 * agent/tool/model/workflow spans show up in the same Jaeger UI as the
 * hand-instrumented withSpan() calls, correctly nested, and share the exact
 * traceId Mastra generated (Mastra documents its traceId as "OTel-compatible,
 * 32 hex chars" — this is clearly the intended integration point).
 */

import {
  trace,
  context as otelContext,
  SpanKind,
  SpanStatusCode,
  TraceFlags,
  type Context,
  type Span as OtelSpan,
} from "@opentelemetry/api";
import { BaseExporter } from "@mastra/observability";
import type { BaseExporterConfig } from "@mastra/observability";
import { TracingEventType, SpanType } from "@mastra/core/observability";
import type { TracingEvent, AnyExportedSpan } from "@mastra/core/observability";

const TRACER_NAME = "lexguard-mastra";

// OTel wants lowercase hex, exactly 32 chars (trace) or 16 chars (span).
// Mastra's traceId is documented as already OTel-compatible; span ids are
// normalized defensively in case of a length mismatch.
function normalizeHex(id: string | undefined, length: number): string {
  const hex = (id ?? "").replace(/[^0-9a-f]/gi, "").toLowerCase();
  if (hex.length === 0) return "0".repeat(length);
  if (hex.length >= length) return hex.slice(0, length);
  return hex.padStart(length, "0");
}

const CLIENT_SPAN_TYPES = new Set<string>([
  SpanType.MODEL_GENERATION,
  SpanType.MODEL_INFERENCE,
  SpanType.RAG_EMBEDDING,
  SpanType.RAG_VECTOR_OPERATION,
  SpanType.MCP_TOOL_CALL,
]);

function flattenAttributes(span: AnyExportedSpan): Record<string, string | number | boolean> {
  const out: Record<string, string | number | boolean> = {
    "mastra.span_type": span.type,
  };
  if (span.entityId) out["mastra.entity_id"] = span.entityId;
  if (span.entityName) out["mastra.entity_name"] = span.entityName;
  if (span.entityType) out["mastra.entity_type"] = String(span.entityType);
  if (span.isRootSpan) out["mastra.is_root_span"] = true;

  const attrs = (span.attributes ?? {}) as Record<string, unknown>;
  for (const [key, value] of Object.entries(attrs)) {
    if (value === undefined || value === null) continue;
    if (typeof value === "object") {
      try {
        out[`mastra.${key}`] = JSON.stringify(value);
      } catch {
        // unserializable — skip rather than throw
      }
    } else {
      out[`mastra.${key}`] = value as string | number | boolean;
    }
  }
  return out;
}

export class MastraOtelBridgeExporter extends BaseExporter {
  name = "mastra-otel-bridge";
  #activeSpans = new Map<string, OtelSpan>();

  constructor(config?: BaseExporterConfig) {
    super(config);
  }

  protected async _exportTracingEvent(event: TracingEvent): Promise<void> {
    const { type, exportedSpan } = event;
    const traceId = normalizeHex(exportedSpan.traceId, 32);

    if (type === TracingEventType.SPAN_STARTED) {
      const parentOtelSpan = exportedSpan.parentSpanId
        ? this.#activeSpans.get(exportedSpan.parentSpanId)
        : undefined;

      let parentContext: Context;
      if (parentOtelSpan) {
        parentContext = trace.setSpan(otelContext.active(), parentOtelSpan);
      } else {
        // No locally-tracked parent (true root span, or the parent was
        // dropped/filtered) — force the traceId Mastra already generated by
        // wrapping a synthetic remote SpanContext as the parent. This is the
        // standard OTel bridging pattern for adopting externally-issued ids.
        parentContext = trace.setSpan(
          otelContext.active(),
          trace.wrapSpanContext({
            traceId,
            spanId: normalizeHex(exportedSpan.parentSpanId, 16),
            traceFlags: TraceFlags.SAMPLED,
            isRemote: true,
          })
        );
      }

      const tracer = trace.getTracer(TRACER_NAME);
      const span = tracer.startSpan(
        exportedSpan.name,
        {
          startTime: exportedSpan.startTime,
          kind: CLIENT_SPAN_TYPES.has(exportedSpan.type) ? SpanKind.CLIENT : SpanKind.INTERNAL,
          attributes: flattenAttributes(exportedSpan),
        },
        parentContext
      );
      this.#activeSpans.set(exportedSpan.id, span);
      return;
    }

    const span = this.#activeSpans.get(exportedSpan.id);
    if (!span) return; // best-effort: update/end for a span we never saw start

    span.setAttributes(flattenAttributes(exportedSpan));

    if (exportedSpan.errorInfo) {
      span.recordException({
        name: exportedSpan.errorInfo.name ?? "Error",
        message: exportedSpan.errorInfo.message,
        stack: exportedSpan.errorInfo.stack,
      });
      span.setStatus({ code: SpanStatusCode.ERROR, message: exportedSpan.errorInfo.message });
    } else if (type === TracingEventType.SPAN_ENDED) {
      span.setStatus({ code: SpanStatusCode.OK });
    }

    if (type === TracingEventType.SPAN_ENDED) {
      span.end(exportedSpan.endTime ?? new Date());
      this.#activeSpans.delete(exportedSpan.id);
    }
  }

  override async shutdown(): Promise<void> {
    const now = new Date();
    for (const [id, span] of this.#activeSpans) {
      span.setStatus({ code: SpanStatusCode.ERROR, message: "Exporter shut down with span still open" });
      span.end(now);
      this.#activeSpans.delete(id);
    }
    await super.shutdown();
  }
}
